#  Configuration file for tpRigToolkits-core

tools:
  - namemanager
  - renamer
  - jointorient
  - controlrig
  - symmesh
  - rigtoolbox
  - rigscript
  # - rigbuilder
  # - rignode
  - spaceswitcher
  - skeletoncreator
  - jointfacialrig
  - interpolateit
  - musclespline
  - puppeteer