#  Configuration file for tpRigToolkit-tools-rigbuilder-dccs-maya

# List that defines the import order of the tool modules
import_order: []

# List that defines the list of modules that will be skipped during import/reload process
skip_modules: []